spring.application.name=Banking-System
server.port=8080
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/banking-system?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=2005
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# lab10 mailru tolko
spring.mail.host=smtp.mail.ru
spring.mail.port=587
spring.mail.username=diastleubergenov@mail.ru
spring.mail.password=De0bxEYX1LvpwxLHZxtK
spring.mail.from-name=Test Bank
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=false
